### ISSUE TITLE
Starting and loading an activity takes up to 30 seconds - ANR

### ISSUE THREAD

**Issue by bardss** [AdevintaSpain/Leku#374] opened 2023-03-29 11:46 UTC
**Describe the bug**
LocationPickerActivity is loading up to 30 seconds.
Some devices throw an ANR.

**To Reproduce**
Just opening an LocationPickerActivity.

**Expected behavior**
Load quicker, how it used to be.
We use Leku library in production since 2017. Issue appear recently.

**Info Required**
Until release month ago, we used versions (worked fine):
- `com.adevinta.android:leku:9.1.4`
- `com.google.android.gms:play-services-location:18.1.0`

Issue appeared when we bumped location services to the newest version of play location services, so:
- `com.adevinta.android:leku:9.1.4`
- `com.google.android.gms:play-services-location:21.0.1`

I also tested it with newest version of Leku library and issue **still exist**:
- `com.adevinta.android:leku:10.1.1`
- `com.google.android.gms:play-services-location:21.0.1`

I tested it with different version for compatibility those versions look like last ones that work together properly without long loading issue:
- `com.adevinta.android:leku:9.1.4`
- `com.google.android.gms:play-services-location:20.0.0`

That is how I initialize `LocationPickerActivity`:
```
            val locationPickerIntent = LocationPickerActivity.Builder()
                .withLocation(
                    latitude ?: DEFAULT_LATITUDE,
                    longitude ?: DEFAULT_LONGITUDE
                )
                .withGeolocApiKey(API_KEY)
                .withSearchZone(EVENT.SEARCH_ZONE_SPAIN)
                .withDefaultLocaleSearchZone()
                .shouldReturnOkOnBackPressed()
                .withSatelliteViewHidden()
                .withGooglePlacesApiKey(API_KEY)
                .withGoogleTimeZoneEnabled()
                .withUnnamedRoadHidden()
                .build(it)
```

and then start an activity for a result.

Our target/support sdk:
```
    minSdkVersion = 23
    targetSdkVersion = 33
    compileSdkVersion = 33
```

- Which version of the library do you actually use?
9.1.14 / 10.1.1

- Do you have the localization permission granted?
Yes.

- Are you sending parameters to the activity through the bundle?
No.

- Android monitor shows any log related to the library when the error is shown?

- Any other thing that could help me to reproduce the error?

**Screenshots**

**Smartphone:**
 - Device: Pixel 7, Android 13
 - Emulator: Pixel 4, API 29
 - Emulator: Nexus 5X, API 23
and some other devices from people that reported me a bug.

**Additional context**
Issue exist while using both debug and production api keys.

In readme you state that **supported google location version is 18.1.0** but I also see [library bump to 21.0.1](https://github.com/AdevintaSpain/Leku/releases/tag/v10.1.1). Which one is a truth? Is 18.1.0 an maximum supported version?

Let me know if I can provide any more context.

**Comment by ferranpons** [comment] 2023-05-17 08:29
@bardss I'm trying to reproduce it but I'm not able to raise an ANR on opening the LocacionPickerActivity. Please could you provide more context?

Are you opening it from a Fragment? Activity? Using some kind of navigation pattern? 
When building it which is the context are you using (I see an "it" on your code)?
Is it possible that ANR is raised there but the LocationPickerActivity is not the cause? Maybe you have a leak somewhere else and it is being stuck on that activity by chance?

**Comment by ferranpons** [comment] 2023-08-21 11:12
@bardss I assume you solved the problem. I close the issue. If you are still experiencing this issue please let me know.

**Closed** 2023-08-21 11:13 UTC
Labels: cannot reproduce
